spring:
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5
    encoding: utf-8
    suffix: .html
    cache: false
  session:
    store-type: redis
  redis:
    database: 0
    host: 172.18.20.1
    password: E9T9E9TPU5
    port: 6379
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 4000MB
  application:
    name: sogonWeb
server:
  port: 8090

#定时任务调度
xxl:
  job:
    admin:
    #addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address:
      ip:
      #port: 9999
      logpath: /home/centos/logs/xxl-job/jobhandler
      logretentiondays: -1
      appname: ams-training-xxl-job
    accessToken: