spring:
  profiles:
    #dev开发环境
    active: anno,common,data,domain,service,rest4web,web
    #active: anno,common,dataPre,domain,service,rest4web,web
    #prd生产环境
    #active: annoWebPrd,commonWebPrd,dataWebPrd,domainWebPrd,serviceWebPrd,restWebPrd,webPrd
    #云计算环境
    #active: annoWebPrd,commonWebPrd,dataWebPrd_sugon,domainWebPrd,serviceWebPrd,restWebPrd,webPrd_sugon
