spring:
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5
    encoding: utf-8
    suffix: .html
    cache: false
  session:
    store-type: redis
  redis:
    database: 0
    host: 192.168.217.142
    password: root
    port: 6379

server:
  port: 8090