spring:
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5
    encoding: utf-8
    suffix: .html
    cache: false
  session:
    store-type: redis
  redis:
    database: 0
    host: 192.168.217.142
    password: root
    port: 6379
  servlet:
     multipart:
        max-file-size: 2048MB
        max-request-size: 4000MB
  data:
    neo4j:
      uri: bolt://192.168.217.137:7687
      username: neo4j
      password: neo4j

server:
  port: 8090