spring:
  thymeleaf:
    prefix: classpath:/static/
    mode: LEGACYHTML5
    encoding: utf-8
    suffix: .html
    cache: false
  session:
    store-type: redis
  redis:
    database: 0
    host: 172.18.20.1
    password: E9T9E9TPU5
    port: 6379
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 4000MB
  application:
    name: sogonWeb
server:
  port: 8090